-- nvim --clean<CR>:redir file<CR>:highlightjjjjjjjjjjjjjjjjjjjj<CR>:redir END

vim.g.apply_transparency = false

local highlight = {
  ["SpecialKey"] = { guifg = "NvimDarkGrey4" },
  ["EndOfBuffer"] = { link = "NonText" },
  ["TermCursor"] = { cterm = "reverse", gui = "reverse" },
  ["TermCursorNC"] = { cleared = true },
  ["NonText"] = { guifg = "NvimDarkGrey4" },
  ["Directory"] = { ctermfg = 14, guifg = "NvimLightCyan" },
  ["ErrorMsg"] = { ctermfg = 9, guifg = "NvimLightRed" },
  ["IncSearch"] = { link = "CurSearch" },
  ["Search"] = { ctermfg = 0, ctermbg = 11, guifg = "NvimLightGrey1", guibg = "NvimDarkYellow" },
  ["CurSearch"] = { ctermfg = 0, ctermbg = 11, guifg = "NvimDarkGrey1", guibg = "NvimLightYellow" },
  ["MoreMsg"] = { ctermfg = 14, guifg = "NvimLightCyan" },
  ["ModeMsg"] = { ctermfg = 10, guifg = "NvimLightGreen" },
  ["LineNr"] = { guifg = "NvimDarkGrey4" },
  ["LineNrAbove"] = { link = "LineNr" },
  ["LineNrBelow"] = { link = "LineNr" },
  ["CursorLineNr"] = { cterm = "bold", gui = "bold" },
  ["CursorLineSign"] = { link = "SignColumn" },
  ["CursorLineFold"] = { link = "FoldColumn" },
  ["Question"] = { ctermfg = 14, guifg = "NvimLightCyan" },
  ["StatusLine"] = { cterm = "reverse", guifg = "NvimDarkGrey3", guibg = "NvimLightGrey3" },
  ["StatusLineNC"] = { cterm = "bold,underline", guifg = "NvimLightGrey3", guibg = "NvimDarkGrey3" },
  ["WinSeparator"] = { link = "Normal" },
  ["VertSplit"] = { link = "WinSeparator" },
  ["Title"] = { cterm = "bold", gui = "bold", guifg = "NvimLightGrey2" },
  ["Visual"] = { ctermfg = 0, ctermbg = 15, guibg = "NvimDarkGrey4" },
  ["VisualNC"] = { cleared = true },
  ["WarningMsg"] = { ctermfg = 11, guifg = "NvimLightYellow" },
  ["WildMenu"] = { link = "PmenuSel" },
  ["Folded"] = { guifg = "NvimLightGrey4", guibg = "NvimDarkGrey3" },
  ["FoldColumn"] = { link = "SignColumn" },
  ["DiffAdd"] = { ctermfg = 0, ctermbg = 10, guifg = "NvimLightGrey1", guibg = "NvimDarkGreen" },
  ["DiffChange"] = { guifg = "NvimLightGrey1", guibg = "NvimDarkGrey4" },
  ["DiffDelete"] = { cterm = "bold", ctermfg = 9, gui = "bold", guifg = "NvimLightRed" },
  ["DiffText"] = { ctermfg = 0, ctermbg = 14, guifg = "NvimLightGrey1", guibg = "NvimDarkCyan" },
  ["SignColumn"] = { guifg = "NvimDarkGrey4" },
  ["Conceal"] = { guifg = "NvimDarkGrey4" },
  ["SpellBad"] = { cterm = "undercurl", gui = "undercurl", guisp = "NvimLightRed" },
  ["SpellCap"] = { cterm = "undercurl", gui = "undercurl", guisp = "NvimLightYellow" },
  ["SpellRare"] = { cterm = "undercurl", gui = "undercurl", guisp = "NvimLightCyan" },
  ["SpellLocal"] = { cterm = "undercurl", gui = "undercurl", guisp = "NvimLightGreen" },
  ["Pmenu"] = { cterm = "reverse", guibg = "NvimDarkGrey3" },
  ["PmenuSel"] = { cterm = "underline,reverse", guifg = "NvimDarkGrey3", guibg = "NvimLightGrey2", blend = 0 },
  ["PmenuKind"] = { link = "Pmenu" },
  ["PmenuKindSel"] = { link = "PmenuSel" },
  ["PmenuExtra"] = { link = "Pmenu" },
  ["PmenuExtraSel"] = { link = "PmenuSel" },
  ["PmenuSbar"] = { link = "Pmenu" },
  ["PmenuThumb"] = { guibg = "NvimDarkGrey4" },
  ["TabLine"] = { link = "StatusLineNC" },
  ["TabLineSel"] = { cterm = "bold", gui = "bold" },
  ["TabLineFill"] = { link = "TabLine" },
  ["CursorColumn"] = { guibg = "NvimDarkGrey3" },
  ["CursorLine"] = { guibg = "NvimDarkGrey3" },
  ["ColorColumn"] = { cterm = "reverse", guibg = "NvimDarkGrey4" },
  ["QuickFixLine"] = { ctermfg = 14, guifg = "NvimLightCyan" },
  ["Whitespace"] = { link = "NonText" },
  ["NormalNC"] = { cleared = true },
  ["MsgSeparator"] = { link = "StatusLine" },
  ["NormalFloat"] = { guibg = "NvimDarkGrey1" },
  ["MsgArea"] = { cleared = true },
  ["FloatBorder"] = { link = "NormalFloat" },
  ["WinBar"] = { cterm = "bold", gui = "bold", guifg = "NvimLightGrey4", guibg = "NvimDarkGrey1" },
  ["WinBarNC"] = { cterm = "bold", guifg = "NvimLightGrey4", guibg = "NvimDarkGrey1" },
  ["Cursor"] = { guifg = "bg", guibg = "fg" },
  ["FloatTitle"] = { link = "Title" },
  ["FloatFooter"] = { link = "FloatTitle" },
  ["RedrawDebugNormal"] = { cterm = "reverse", gui = "reverse" },
  ["Underlined"] = { cterm = "underline", gui = "underline" },
  ["lCursor"] = { guifg = "bg", guibg = "fg" },
  ["CursorIM"] = { link = "Cursor" },
  ["Substitute"] = { link = "Search" },
  ["VisualNOS"] = { link = "Visual" },
  ["Normal"] = { guifg = "NvimLightGrey2", guibg = "NvimDarkGrey2" },
  ["Character"] = { link = "Constant" },
  ["Constant"] = { guifg = "NvimLightGrey2" },
  ["Number"] = { link = "Constant" },
  ["Boolean"] = { link = "Constant" },
  ["Float"] = { link = "Number" },
  ["Conditional"] = { link = "Statement" },
  ["Statement"] = { cterm = "bold", gui = "bold", guifg = "NvimLightGrey2" },
  ["Repeat"] = { link = "Statement" },
  ["Label"] = { link = "Statement" },
  ["Keyword"] = { link = "Statement" },
  ["Exception"] = { link = "Statement" },
  ["Include"] = { link = "PreProc" },
  ["PreProc"] = { guifg = "NvimLightGrey2" },
  ["Define"] = { link = "PreProc" },
  ["Macro"] = { link = "PreProc" },
  ["PreCondit"] = { link = "PreProc" },
  ["StorageClass"] = { link = "Type" },
  ["Type"] = { guifg = "NvimLightGrey2" },
  ["Structure"] = { link = "Type" },
  ["Typedef"] = { link = "Type" },
  ["Tag"] = { link = "Special" },
  ["Special"] = { ctermfg = 14, guifg = "NvimLightCyan" },
  ["SpecialChar"] = { link = "Special" },
  ["SpecialComment"] = { link = "Special" },
  ["Debug"] = { link = "Special" },
  ["Ignore"] = { link = "Normal" },
  ["LspCodeLens"] = { link = "NonText" },
  ["LspCodeLensSeparator"] = { link = "LspCodeLens" },
  ["LspInlayHint"] = { link = "NonText" },
  ["LspReferenceRead"] = { link = "LspReferenceText" },
  ["LspReferenceText"] = { link = "Visual" },
  ["LspReferenceWrite"] = { link = "LspReferenceText" },
  ["LspSignatureActiveParameter"] = { link = "Visual" },
  ["SnippetTabstop"] = { link = "Visual" },
  ["DiagnosticFloatingError"] = { link = "DiagnosticError" },
  ["DiagnosticError"] = { ctermfg = 9, guifg = "NvimLightRed" },
  ["DiagnosticFloatingWarn"] = { link = "DiagnosticWarn" },
  ["DiagnosticWarn"] = { ctermfg = 11, guifg = "NvimLightYellow" },
  ["DiagnosticFloatingInfo"] = { link = "DiagnosticInfo" },
  ["DiagnosticInfo"] = { ctermfg = 14, guifg = "NvimLightCyan" },
  ["DiagnosticFloatingHint"] = { link = "DiagnosticHint" },
  ["DiagnosticHint"] = { ctermfg = 12, guifg = "NvimLightBlue" },
  ["DiagnosticFloatingOk"] = { link = "DiagnosticOk" },
  ["DiagnosticOk"] = { ctermfg = 10, guifg = "NvimLightGreen" },
  ["DiagnosticVirtualTextError"] = { link = "DiagnosticError" },
  ["DiagnosticVirtualTextWarn"] = { link = "DiagnosticWarn" },
  ["DiagnosticVirtualTextInfo"] = { link = "DiagnosticInfo" },
  ["DiagnosticVirtualTextHint"] = { link = "DiagnosticHint" },
  ["DiagnosticVirtualTextOk"] = { link = "DiagnosticOk" },
  ["DiagnosticSignError"] = { link = "DiagnosticError" },
  ["DiagnosticSignWarn"] = { link = "DiagnosticWarn" },
  ["DiagnosticSignInfo"] = { link = "DiagnosticInfo" },
  ["DiagnosticSignHint"] = { link = "DiagnosticHint" },
  ["DiagnosticSignOk"] = { link = "DiagnosticOk" },
  ["DiagnosticUnnecessary"] = { link = "Comment" },
  ["Comment"] = { guifg = "NvimLightGrey4" },
  ["@variable"] = { guifg = "NvimLightGrey2" },
  ["@variable.builtin"] = { link = "Special" },
  ["@variable.parameter.builtin"] = { link = "Special" },
  ["@constant"] = { link = "Constant" },
  ["@constant.builtin"] = { link = "Special" },
  ["@module"] = { link = "Structure" },
  ["@module.builtin"] = { link = "Special" },
  ["@label"] = { link = "Label" },
  ["@string"] = { link = "String" },
  ["String"] = { ctermfg = 10, guifg = "NvimLightGreen" },
  ["@string.regexp"] = { link = "@string.special" },
  ["@string.special"] = { link = "SpecialChar" },
  ["@string.escape"] = { link = "@string.special" },
  ["@string.special.url"] = { link = "Underlined" },
  ["@character"] = { link = "Character" },
  ["@character.special"] = { link = "SpecialChar" },
  ["@boolean"] = { link = "Boolean" },
  ["@number"] = { link = "Number" },
  ["@number.float"] = { link = "Float" },
  ["@type"] = { link = "Type" },
  ["@type.builtin"] = { link = "Special" },
  ["@attribute"] = { link = "Macro" },
  ["@attribute.builtin"] = { link = "Special" },
  ["@property"] = { link = "Identifier" },
  ["Identifier"] = { ctermfg = 12, guifg = "NvimLightBlue" },
  ["@function"] = { link = "Function" },
  ["Function"] = { ctermfg = 14, guifg = "NvimLightCyan" },
  ["@function.builtin"] = { link = "Special" },
  ["@constructor"] = { link = "Special" },
  ["@operator"] = { link = "Operator" },
  ["Operator"] = { guifg = "NvimLightGrey2" },
  ["@keyword"] = { link = "Keyword" },
  ["@punctuation"] = { link = "Delimiter" },
  ["Delimiter"] = { guifg = "NvimLightGrey2" },
  ["@punctuation.special"] = { link = "Special" },
  ["@comment"] = { link = "Comment" },
  ["@comment.error"] = { link = "DiagnosticError" },
  ["@comment.warning"] = { link = "DiagnosticWarn" },
  ["@comment.note"] = { link = "DiagnosticInfo" },
  ["@comment.todo"] = { link = "Todo" },
  ["Todo"] = { cterm = "bold", gui = "bold", guifg = "NvimLightGrey2" },
  ["@markup"] = { link = "Special" },
  ["@markup.strong"] = { cterm = "bold", gui = "bold" },
  ["@markup.italic"] = { cterm = "italic", gui = "italic" },
  ["@markup.strikethrough"] = { cterm = "strikethrough", gui = "strikethrough" },
  ["@markup.underline"] = { cterm = "underline", gui = "underline" },
  ["@markup.heading"] = { link = "Title" },
  ["@markup.link"] = { link = "Underlined" },
  ["@diff"] = { cleared = true },
  ["@diff.plus"] = { link = "Added" },
  ["Added"] = { ctermfg = 10, guifg = "NvimLightGreen" },
  ["@diff.minus"] = { link = "Removed" },
  ["Removed"] = { ctermfg = 9, guifg = "NvimLightRed" },
  ["@diff.delta"] = { link = "Changed" },
  ["Changed"] = { ctermfg = 14, guifg = "NvimLightCyan" },
  ["@tag"] = { link = "Tag" },
  ["@tag.builtin"] = { link = "Special" },
  ["@lsp"] = { cleared = true },
  ["@lsp.type.class"] = { link = "@type" },
  ["@lsp.type.comment"] = { link = "@comment" },
  ["@lsp.type.decorator"] = { link = "@attribute" },
  ["@lsp.type.enum"] = { link = "@type" },
  ["@lsp.type.enumMember"] = { link = "@constant" },
  ["@lsp.type.event"] = { link = "@type" },
  ["@lsp.type.function"] = { link = "@function" },
  ["@lsp.type.interface"] = { link = "@type" },
  ["@lsp.type.keyword"] = { link = "@keyword" },
  ["@lsp.type.macro"] = { link = "@constant.macro" },
  ["@lsp.type.method"] = { link = "@function.method" },
  ["@lsp.type.modifier"] = { link = "@type.qualifier" },
  ["@lsp.type.namespace"] = { link = "@module" },
  ["@lsp.type.number"] = { link = "@number" },
  ["@lsp.type.operator"] = { link = "@operator" },
  ["@lsp.type.parameter"] = { link = "@variable.parameter" },
  ["@lsp.type.property"] = { link = "@property" },
  ["@lsp.type.regexp"] = { link = "@string.regexp" },
  ["@lsp.type.string"] = { link = "@string" },
  ["@lsp.type.struct"] = { link = "@type" },
  ["@lsp.type.type"] = { link = "@type" },
  ["@lsp.type.typeParameter"] = { link = "@type.definition" },
  ["@lsp.type.variable"] = { link = "@variable" },
  ["@lsp.mod.deprecated"] = { link = "DiagnosticDeprecated" },
  ["DiagnosticDeprecated"] = { cterm = "strikethrough", gui = "strikethrough", guisp = "NvimLightRed" },
  ["FloatShadow"] = { ctermbg = 0, guibg = "NvimDarkGrey4", blend = 80 },
  ["FloatShadowThrough"] = { ctermbg = 0, guibg = "NvimDarkGrey4", blend = 100 },
  ["MatchParen"] = { cterm = "bold,underline", gui = "bold", guibg = "NvimDarkGrey4" },
  ["RedrawDebugClear"] = { ctermfg = 0, ctermbg = 11, guibg = "NvimDarkYellow" },
  ["RedrawDebugComposed"] = { ctermfg = 0, ctermbg = 10, guibg = "NvimDarkGreen" },
  ["RedrawDebugRecompose"] = { ctermfg = 0, ctermbg = 9, guibg = "NvimDarkRed" },
  ["Error"] = { ctermfg = 0, ctermbg = 9, guifg = "NvimLightGrey1", guibg = "NvimDarkRed" },
  ["DiagnosticUnderlineError"] = { cterm = "underline", gui = "underline", guisp = "NvimLightRed" },
  ["DiagnosticUnderlineWarn"] = { cterm = "underline", gui = "underline", guisp = "NvimLightYellow" },
  ["DiagnosticUnderlineInfo"] = { cterm = "underline", gui = "underline", guisp = "NvimLightCyan" },
  ["DiagnosticUnderlineHint"] = { cterm = "underline", gui = "underline", guisp = "NvimLightBlue" },
  ["DiagnosticUnderlineOk"] = { cterm = "underline", gui = "underline", guisp = "NvimLightGreen" },
  ["NvimInternalError"] = { ctermfg = 9, ctermbg = 9, guifg = "Red", guibg = "Red" },
  ["NvimAssignment"] = { link = "Operator" },
  ["NvimPlainAssignment"] = { link = "NvimAssignment" },
  ["NvimAugmentedAssignment"] = { link = "NvimAssignment" },
  ["NvimAssignmentWithAddition"] = { link = "NvimAugmentedAssignment" },
  ["NvimAssignmentWithSubtraction"] = { link = "NvimAugmentedAssignment" },
  ["NvimAssignmentWithConcatenation"] = { link = "NvimAugmentedAssignment" },
  ["NvimOperator"] = { link = "Operator" },
  ["NvimUnaryOperator"] = { link = "NvimOperator" },
  ["NvimUnaryPlus"] = { link = "NvimUnaryOperator" },
  ["NvimUnaryMinus"] = { link = "NvimUnaryOperator" },
  ["NvimNot"] = { link = "NvimUnaryOperator" },
  ["NvimBinaryOperator"] = { link = "NvimOperator" },
  ["NvimComparison"] = { link = "NvimBinaryOperator" },
  ["NvimComparisonModifier"] = { link = "NvimComparison" },
  ["NvimBinaryPlus"] = { link = "NvimBinaryOperator" },
  ["NvimBinaryMinus"] = { link = "NvimBinaryOperator" },
  ["NvimConcat"] = { link = "NvimBinaryOperator" },
  ["NvimConcatOrSubscript"] = { link = "NvimConcat" },
  ["NvimOr"] = { link = "NvimBinaryOperator" },
  ["NvimAnd"] = { link = "NvimBinaryOperator" },
  ["NvimMultiplication"] = { link = "NvimBinaryOperator" },
  ["NvimDivision"] = { link = "NvimBinaryOperator" },
  ["NvimMod"] = { link = "NvimBinaryOperator" },
  ["NvimTernary"] = { link = "NvimOperator" },
  ["NvimTernaryColon"] = { link = "NvimTernary" },
  ["NvimParenthesis"] = { link = "Delimiter" },
  ["NvimLambda"] = { link = "NvimParenthesis" },
  ["NvimNestingParenthesis"] = { link = "NvimParenthesis" },
  ["NvimCallingParenthesis"] = { link = "NvimParenthesis" },
  ["NvimSubscript"] = { link = "NvimParenthesis" },
  ["NvimSubscriptBracket"] = { link = "NvimSubscript" },
  ["NvimSubscriptColon"] = { link = "NvimSubscript" },
  ["NvimCurly"] = { link = "NvimSubscript" },
  ["NvimContainer"] = { link = "NvimParenthesis" },
  ["NvimDict"] = { link = "NvimContainer" },
  ["NvimList"] = { link = "NvimContainer" },
  ["NvimIdentifier"] = { link = "Identifier" },
  ["NvimIdentifierScope"] = { link = "NvimIdentifier" },
  ["NvimIdentifierScopeDelimiter"] = { link = "NvimIdentifier" },
  ["NvimIdentifierName"] = { link = "NvimIdentifier" },
  ["NvimIdentifierKey"] = { link = "NvimIdentifier" },
  ["NvimColon"] = { link = "Delimiter" },
  ["NvimComma"] = { link = "Delimiter" },
  ["NvimArrow"] = { link = "Delimiter" },
  ["NvimRegister"] = { link = "SpecialChar" },
  ["NvimNumber"] = { link = "Number" },
  ["NvimFloat"] = { link = "NvimNumber" },
  ["NvimNumberPrefix"] = { link = "Type" },
  ["NvimOptionSigil"] = { link = "Type" },
  ["NvimOptionName"] = { link = "NvimIdentifier" },
  ["NvimOptionScope"] = { link = "NvimIdentifierScope" },
  ["NvimOptionScopeDelimiter"] = { link = "NvimIdentifierScopeDelimiter" },
  ["NvimEnvironmentSigil"] = { link = "NvimOptionSigil" },
  ["NvimEnvironmentName"] = { link = "NvimIdentifier" },
  ["NvimString"] = { link = "String" },
  ["NvimStringBody"] = { link = "NvimString" },
  ["NvimStringQuote"] = { link = "NvimString" },
  ["NvimStringSpecial"] = { link = "SpecialChar" },
  ["NvimSingleQuote"] = { link = "NvimStringQuote" },
  ["NvimSingleQuotedBody"] = { link = "NvimStringBody" },
  ["NvimSingleQuotedQuote"] = { link = "NvimStringSpecial" },
  ["NvimDoubleQuote"] = { link = "NvimStringQuote" },
  ["NvimDoubleQuotedBody"] = { link = "NvimStringBody" },
  ["NvimDoubleQuotedEscape"] = { link = "NvimStringSpecial" },
  ["NvimFigureBrace"] = { link = "NvimInternalError" },
  ["NvimSingleQuotedUnknownEscape"] = { link = "NvimInternalError" },
  ["NvimSpacing"] = { link = "Normal" },
  ["NvimInvalidSingleQuotedUnknownEscape"] = { link = "NvimInternalError" },
  ["NvimInvalid"] = { link = "Error" },
  ["NvimInvalidAssignment"] = { link = "NvimInvalid" },
  ["NvimInvalidPlainAssignment"] = { link = "NvimInvalidAssignment" },
  ["NvimInvalidAugmentedAssignment"] = { link = "NvimInvalidAssignment" },
  ["NvimInvalidAssignmentWithAddition"] = { link = "NvimInvalidAugmentedAssignment" },
  ["NvimInvalidAssignmentWithSubtraction"] = { link = "NvimInvalidAugmentedAssignment" },
  ["NvimInvalidAssignmentWithConcatenation"] = { link = "NvimInvalidAugmentedAssignment" },
  ["NvimInvalidOperator"] = { link = "NvimInvalid" },
  ["NvimInvalidUnaryOperator"] = { link = "NvimInvalidOperator" },
  ["NvimInvalidUnaryPlus"] = { link = "NvimInvalidUnaryOperator" },
  ["NvimInvalidUnaryMinus"] = { link = "NvimInvalidUnaryOperator" },
  ["NvimInvalidNot"] = { link = "NvimInvalidUnaryOperator" },
  ["NvimInvalidBinaryOperator"] = { link = "NvimInvalidOperator" },
  ["NvimInvalidComparison"] = { link = "NvimInvalidBinaryOperator" },
  ["NvimInvalidComparisonModifier"] = { link = "NvimInvalidComparison" },
  ["NvimInvalidBinaryPlus"] = { link = "NvimInvalidBinaryOperator" },
  ["NvimInvalidBinaryMinus"] = { link = "NvimInvalidBinaryOperator" },
  ["NvimInvalidConcat"] = { link = "NvimInvalidBinaryOperator" },
  ["NvimInvalidConcatOrSubscript"] = { link = "NvimInvalidConcat" },
  ["NvimInvalidOr"] = { link = "NvimInvalidBinaryOperator" },
  ["NvimInvalidAnd"] = { link = "NvimInvalidBinaryOperator" },
  ["NvimInvalidMultiplication"] = { link = "NvimInvalidBinaryOperator" },
  ["NvimInvalidDivision"] = { link = "NvimInvalidBinaryOperator" },
  ["NvimInvalidMod"] = { link = "NvimInvalidBinaryOperator" },
  ["NvimInvalidTernary"] = { link = "NvimInvalidOperator" },
  ["NvimInvalidTernaryColon"] = { link = "NvimInvalidTernary" },
  ["NvimInvalidDelimiter"] = { link = "NvimInvalid" },
  ["NvimInvalidParenthesis"] = { link = "NvimInvalidDelimiter" },
  ["NvimInvalidLambda"] = { link = "NvimInvalidParenthesis" },
  ["NvimInvalidNestingParenthesis"] = { link = "NvimInvalidParenthesis" },
  ["NvimInvalidCallingParenthesis"] = { link = "NvimInvalidParenthesis" },
  ["NvimInvalidSubscript"] = { link = "NvimInvalidParenthesis" },
  ["NvimInvalidSubscriptBracket"] = { link = "NvimInvalidSubscript" },
  ["NvimInvalidSubscriptColon"] = { link = "NvimInvalidSubscript" },
  ["NvimInvalidCurly"] = { link = "NvimInvalidSubscript" },
  ["NvimInvalidContainer"] = { link = "NvimInvalidParenthesis" },
  ["NvimInvalidDict"] = { link = "NvimInvalidContainer" },
  ["NvimInvalidList"] = { link = "NvimInvalidContainer" },
  ["NvimInvalidValue"] = { link = "NvimInvalid" },
  ["NvimInvalidIdentifier"] = { link = "NvimInvalidValue" },
  ["NvimInvalidIdentifierScope"] = { link = "NvimInvalidIdentifier" },
  ["NvimInvalidIdentifierScopeDelimiter"] = { link = "NvimInvalidIdentifier" },
  ["NvimInvalidIdentifierName"] = { link = "NvimInvalidIdentifier" },
  ["NvimInvalidIdentifierKey"] = { link = "NvimInvalidIdentifier" },
  ["NvimInvalidColon"] = { link = "NvimInvalidDelimiter" },
  ["NvimInvalidComma"] = { link = "NvimInvalidDelimiter" },
  ["NvimInvalidArrow"] = { link = "NvimInvalidDelimiter" },
  ["NvimInvalidRegister"] = { link = "NvimInvalidValue" },
  ["NvimInvalidNumber"] = { link = "NvimInvalidValue" },
  ["NvimInvalidFloat"] = { link = "NvimInvalidNumber" },
  ["NvimInvalidNumberPrefix"] = { link = "NvimInvalidNumber" },
  ["NvimInvalidOptionSigil"] = { link = "NvimInvalidIdentifier" },
  ["NvimInvalidOptionName"] = { link = "NvimInvalidIdentifier" },
  ["NvimInvalidOptionScope"] = { link = "NvimInvalidIdentifierScope" },
  ["NvimInvalidOptionScopeDelimiter"] = { link = "NvimInvalidIdentifierScopeDelimiter" },
  ["NvimInvalidEnvironmentSigil"] = { link = "NvimInvalidOptionSigil" },
  ["NvimInvalidEnvironmentName"] = { link = "NvimInvalidIdentifier" },
  ["NvimInvalidString"] = { link = "NvimInvalidValue" },
  ["NvimInvalidStringBody"] = { link = "NvimStringBody" },
  ["NvimInvalidStringQuote"] = { link = "NvimInvalidString" },
  ["NvimInvalidStringSpecial"] = { link = "NvimStringSpecial" },
  ["NvimInvalidSingleQuote"] = { link = "NvimInvalidStringQuote" },
  ["NvimInvalidSingleQuotedBody"] = { link = "NvimInvalidStringBody" },
  ["NvimInvalidSingleQuotedQuote"] = { link = "NvimInvalidStringSpecial" },
  ["NvimInvalidDoubleQuote"] = { link = "NvimInvalidStringQuote" },
  ["NvimInvalidDoubleQuotedBody"] = { link = "NvimInvalidStringBody" },
  ["NvimInvalidDoubleQuotedEscape"] = { link = "NvimInvalidStringSpecial" },
  ["NvimInvalidDoubleQuotedUnknownEscape"] = { link = "NvimInvalidValue" },
  ["NvimInvalidFigureBrace"] = { link = "NvimInvalidDelimiter" },
  ["NvimInvalidSpacing"] = { link = "ErrorMsg" },
  ["NvimDoubleQuotedUnknownEscape"] = { link = "NvimInvalidValue" },
}

return highlight

--[[

{
  AliceBlue = "#f0f8ff",
  AntiqueWhite = "#faebd7",
  AntiqueWhite1 = "#ffefdb",
  AntiqueWhite2 = "#eedfcc",
  AntiqueWhite3 = "#cdc0b0",
  AntiqueWhite4 = "#8b8378",
  Aqua = "#00ffff",
  Aquamarine = "#7fffd4",
  Aquamarine1 = "#7fffd4",
  Aquamarine2 = "#76eec6",
  Aquamarine3 = "#66cdaa",
  Aquamarine4 = "#458b74",
  Azure = "#f0ffff",
  Azure1 = "#f0ffff",
  Azure2 = "#e0eeee",
  Azure3 = "#c1cdcd",
  Azure4 = "#838b8b",
  Beige = "#f5f5dc",
  Bisque = "#ffe4c4",
  Bisque1 = "#ffe4c4",
  Bisque2 = "#eed5b7",
  Bisque3 = "#cdb79e",
  Bisque4 = "#8b7d6b",
  Black = "#000000",
  BlanchedAlmond = "#ffebcd",
  Blue = "#0000ff",
  Blue1 = "#0000ff",
  Blue2 = "#0000ee",
  Blue3 = "#0000cd",
  Blue4 = "#00008b",
  BlueViolet = "#8a2be2",
  Brown = "#a52a2a",
  Brown1 = "#ff4040",
  Brown2 = "#ee3b3b",
  Brown3 = "#cd3333",
  Brown4 = "#8b2323",
  BurlyWood = "#deb887",
  Burlywood1 = "#ffd39b",
  Burlywood2 = "#eec591",
  Burlywood3 = "#cdaa7d",
  Burlywood4 = "#8b7355",
  CadetBlue = "#5f9ea0",
  CadetBlue1 = "#98f5ff",
  CadetBlue2 = "#8ee5ee",
  CadetBlue3 = "#7ac5cd",
  CadetBlue4 = "#53868b",
  ChartReuse = "#7fff00",
  Chartreuse1 = "#7fff00",
  Chartreuse2 = "#76ee00",
  Chartreuse3 = "#66cd00",
  Chartreuse4 = "#458b00",
  Chocolate = "#d2691e",
  Chocolate1 = "#ff7f24",
  Chocolate2 = "#ee7621",
  Chocolate3 = "#cd661d",
  Chocolate4 = "#8b4513",
  Coral = "#ff7f50",
  Coral1 = "#ff7256",
  Coral2 = "#ee6a50",
  Coral3 = "#cd5b45",
  Coral4 = "#8b3e2f",
  CornFlowerBlue = "#6495ed",
  Cornsilk = "#fff8dc",
  Cornsilk1 = "#fff8dc",
  Cornsilk2 = "#eee8cd",
  Cornsilk3 = "#cdc8b1",
  Cornsilk4 = "#8b8878",
  Crimson = "#dc143c",
  Cyan = "#00ffff",
  Cyan1 = "#00ffff",
  Cyan2 = "#00eeee",
  Cyan3 = "#00cdcd",
  Cyan4 = "#008b8b",
  DarkBlue = "#00008b",
  DarkCyan = "#008b8b",
  DarkGoldenrod = "#b8860b",
  DarkGoldenrod1 = "#ffb90f",
  DarkGoldenrod2 = "#eead0e",
  DarkGoldenrod3 = "#cd950c",
  DarkGoldenrod4 = "#8b6508",
  DarkGray = "#a9a9a9",
  DarkGreen = "#006400",
  DarkGrey = "#a9a9a9",
  DarkKhaki = "#bdb76b",
  DarkMagenta = "#8b008b",
  DarkOliveGreen = "#556b2f",
  DarkOliveGreen1 = "#caff70",
  DarkOliveGreen2 = "#bcee68",
  DarkOliveGreen3 = "#a2cd5a",
  DarkOliveGreen4 = "#6e8b3d",
  DarkOrange = "#ff8c00",
  DarkOrange1 = "#ff7f00",
  DarkOrange2 = "#ee7600",
  DarkOrange3 = "#cd6600",
  DarkOrange4 = "#8b4500",
  DarkOrchid = "#9932cc",
  DarkOrchid1 = "#bf3eff",
  DarkOrchid2 = "#b23aee",
  DarkOrchid3 = "#9a32cd",
  DarkOrchid4 = "#68228b",
  DarkRed = "#8b0000",
  DarkSalmon = "#e9967a",
  DarkSeaGreen = "#8fbc8f",
  DarkSeaGreen1 = "#c1ffc1",
  DarkSeaGreen2 = "#b4eeb4",
  DarkSeaGreen3 = "#9bcd9b",
  DarkSeaGreen4 = "#698b69",
  DarkSlateBlue = "#483d8b",
  DarkSlateGray = "#2f4f4f",
  DarkSlateGray1 = "#97ffff",
  DarkSlateGray2 = "#8deeee",
  DarkSlateGray3 = "#79cdcd",
  DarkSlateGray4 = "#528b8b",
  DarkSlateGrey = "#2f4f4f",
  DarkTurquoise = "#00ced1",
  DarkViolet = "#9400d3",
  DarkYellow = "#bbbb00",
  DeepPink = "#ff1493",
  DeepPink1 = "#ff1493",
  DeepPink2 = "#ee1289",
  DeepPink3 = "#cd1076",
  DeepPink4 = "#8b0a50",
  DeepSkyBlue = "#00bfff",
  DeepSkyBlue1 = "#00bfff",
  DeepSkyBlue2 = "#00b2ee",
  DeepSkyBlue3 = "#009acd",
  DeepSkyBlue4 = "#00688b",
  DimGray = "#696969",
  DimGrey = "#696969",
  DodgerBlue = "#1e90ff",
  DodgerBlue1 = "#1e90ff",
  DodgerBlue2 = "#1c86ee",
  DodgerBlue3 = "#1874cd",
  DodgerBlue4 = "#104e8b",
  Firebrick = "#b22222",
  Firebrick1 = "#ff3030",
  Firebrick2 = "#ee2c2c",
  Firebrick3 = "#cd2626",
  Firebrick4 = "#8b1a1a",
  FloralWhite = "#fffaf0",
  ForestGreen = "#228b22",
  Fuchsia = "#ff00ff",
  Gainsboro = "#dcdcdc",
  GhostWhite = "#f8f8ff",
  Gold = "#ffd700",
  Gold1 = "#ffd700",
  Gold2 = "#eec900",
  Gold3 = "#cdad00",
  Gold4 = "#8b7500",
  Goldenrod = "#daa520",
  Goldenrod1 = "#ffc125",
  Goldenrod2 = "#eeb422",
  Goldenrod3 = "#cd9b1d",
  Goldenrod4 = "#8b6914",
  Gray = "#808080",
  Gray0 = "#000000",
  Gray1 = "#030303",
  Gray10 = "#1a1a1a",
  Gray100 = "#ffffff",
  Gray11 = "#1c1c1c",
  Gray12 = "#1f1f1f",
  Gray13 = "#212121",
  Gray14 = "#242424",
  Gray15 = "#262626",
  Gray16 = "#292929",
  Gray17 = "#2b2b2b",
  Gray18 = "#2e2e2e",
  Gray19 = "#303030",
  Gray2 = "#050505",
  Gray20 = "#333333",
  Gray21 = "#363636",
  Gray22 = "#383838",
  Gray23 = "#3b3b3b",
  Gray24 = "#3d3d3d",
  Gray25 = "#404040",
  Gray26 = "#424242",
  Gray27 = "#454545",
  Gray28 = "#474747",
  Gray29 = "#4a4a4a",
  Gray3 = "#080808",
  Gray30 = "#4d4d4d",
  Gray31 = "#4f4f4f",
  Gray32 = "#525252",
  Gray33 = "#545454",
  Gray34 = "#575757",
  Gray35 = "#595959",
  Gray36 = "#5c5c5c",
  Gray37 = "#5e5e5e",
  Gray38 = "#616161",
  Gray39 = "#636363",
  Gray4 = "#0a0a0a",
  Gray40 = "#666666",
  Gray41 = "#696969",
  Gray42 = "#6b6b6b",
  Gray43 = "#6e6e6e",
  Gray44 = "#707070",
  Gray45 = "#737373",
  Gray46 = "#757575",
  Gray47 = "#787878",
  Gray48 = "#7a7a7a",
  Gray49 = "#7d7d7d",
  Gray5 = "#0d0d0d",
  Gray50 = "#7f7f7f",
  Gray51 = "#828282",
  Gray52 = "#858585",
  Gray53 = "#878787",
  Gray54 = "#8a8a8a",
  Gray55 = "#8c8c8c",
  Gray56 = "#8f8f8f",
  Gray57 = "#919191",
  Gray58 = "#949494",
  Gray59 = "#969696",
  Gray6 = "#0f0f0f",
  Gray60 = "#999999",
  Gray61 = "#9c9c9c",
  Gray62 = "#9e9e9e",
  Gray63 = "#a1a1a1",
  Gray64 = "#a3a3a3",
  Gray65 = "#a6a6a6",
  Gray66 = "#a8a8a8",
  Gray67 = "#ababab",
  Gray68 = "#adadad",
  Gray69 = "#b0b0b0",
  Gray7 = "#121212",
  Gray70 = "#b3b3b3",
  Gray71 = "#b5b5b5",
  Gray72 = "#b8b8b8",
  Gray73 = "#bababa",
  Gray74 = "#bdbdbd",
  Gray75 = "#bfbfbf",
  Gray76 = "#c2c2c2",
  Gray77 = "#c4c4c4",
  Gray78 = "#c7c7c7",
  Gray79 = "#c9c9c9",
  Gray8 = "#141414",
  Gray80 = "#cccccc",
  Gray81 = "#cfcfcf",
  Gray82 = "#d1d1d1",
  Gray83 = "#d4d4d4",
  Gray84 = "#d6d6d6",
  Gray85 = "#d9d9d9",
  Gray86 = "#dbdbdb",
  Gray87 = "#dedede",
  Gray88 = "#e0e0e0",
  Gray89 = "#e3e3e3",
  Gray9 = "#171717",
  Gray90 = "#e5e5e5",
  Gray91 = "#e8e8e8",
  Gray92 = "#ebebeb",
  Gray93 = "#ededed",
  Gray94 = "#f0f0f0",
  Gray95 = "#f2f2f2",
  Gray96 = "#f5f5f5",
  Gray97 = "#f7f7f7",
  Gray98 = "#fafafa",
  Gray99 = "#fcfcfc",
  Green = "#008000",
  Green1 = "#00ff00",
  Green2 = "#00ee00",
  Green3 = "#00cd00",
  Green4 = "#008b00",
  GreenYellow = "#adff2f",
  Grey = "#808080",
  Grey0 = "#000000",
  Grey1 = "#030303",
  Grey10 = "#1a1a1a",
  Grey100 = "#ffffff",
  Grey11 = "#1c1c1c",
  Grey12 = "#1f1f1f",
  Grey13 = "#212121",
  Grey14 = "#242424",
  Grey15 = "#262626",
  Grey16 = "#292929",
  Grey17 = "#2b2b2b",
  Grey18 = "#2e2e2e",
  Grey19 = "#303030",
  Grey2 = "#050505",
  Grey20 = "#333333",
  Grey21 = "#363636",
  Grey22 = "#383838",
  Grey23 = "#3b3b3b",
  Grey24 = "#3d3d3d",
  Grey25 = "#404040",
  Grey26 = "#424242",
  Grey27 = "#454545",
  Grey28 = "#474747",
  Grey29 = "#4a4a4a",
  Grey3 = "#080808",
  Grey30 = "#4d4d4d",
  Grey31 = "#4f4f4f",
  Grey32 = "#525252",
  Grey33 = "#545454",
  Grey34 = "#575757",
  Grey35 = "#595959",
  Grey36 = "#5c5c5c",
  Grey37 = "#5e5e5e",
  Grey38 = "#616161",
  Grey39 = "#636363",
  Grey4 = "#0a0a0a",
  Grey40 = "#666666",
  Grey41 = "#696969",
  Grey42 = "#6b6b6b",
  Grey43 = "#6e6e6e",
  Grey44 = "#707070",
  Grey45 = "#737373",
  Grey46 = "#757575",
  Grey47 = "#787878",
  Grey48 = "#7a7a7a",
  Grey49 = "#7d7d7d",
  Grey5 = "#0d0d0d",
  Grey50 = "#7f7f7f",
  Grey51 = "#828282",
  Grey52 = "#858585",
  Grey53 = "#878787",
  Grey54 = "#8a8a8a",
  Grey55 = "#8c8c8c",
  Grey56 = "#8f8f8f",
  Grey57 = "#919191",
  Grey58 = "#949494",
  Grey59 = "#969696",
  Grey6 = "#0f0f0f",
  Grey60 = "#999999",
  Grey61 = "#9c9c9c",
  Grey62 = "#9e9e9e",
  Grey63 = "#a1a1a1",
  Grey64 = "#a3a3a3",
  Grey65 = "#a6a6a6",
  Grey66 = "#a8a8a8",
  Grey67 = "#ababab",
  Grey68 = "#adadad",
  Grey69 = "#b0b0b0",
  Grey7 = "#121212",
  Grey70 = "#b3b3b3",
  Grey71 = "#b5b5b5",
  Grey72 = "#b8b8b8",
  Grey73 = "#bababa",
  Grey74 = "#bdbdbd",
  Grey75 = "#bfbfbf",
  Grey76 = "#c2c2c2",
  Grey77 = "#c4c4c4",
  Grey78 = "#c7c7c7",
  Grey79 = "#c9c9c9",
  Grey8 = "#141414",
  Grey80 = "#cccccc",
  Grey81 = "#cfcfcf",
  Grey82 = "#d1d1d1",
  Grey83 = "#d4d4d4",
  Grey84 = "#d6d6d6",
  Grey85 = "#d9d9d9",
  Grey86 = "#dbdbdb",
  Grey87 = "#dedede",
  Grey88 = "#e0e0e0",
  Grey89 = "#e3e3e3",
  Grey9 = "#171717",
  Grey90 = "#e5e5e5",
  Grey91 = "#e8e8e8",
  Grey92 = "#ebebeb",
  Grey93 = "#ededed",
  Grey94 = "#f0f0f0",
  Grey95 = "#f2f2f2",
  Grey96 = "#f5f5f5",
  Grey97 = "#f7f7f7",
  Grey98 = "#fafafa",
  Grey99 = "#fcfcfc",
  Honeydew = "#f0fff0",
  Honeydew1 = "#f0fff0",
  Honeydew2 = "#e0eee0",
  Honeydew3 = "#c1cdc1",
  Honeydew4 = "#838b83",
  HotPink = "#ff69b4",
  HotPink1 = "#ff6eb4",
  HotPink2 = "#ee6aa7",
  HotPink3 = "#cd6090",
  HotPink4 = "#8b3a62",
  IndianRed = "#cd5c5c",
  IndianRed1 = "#ff6a6a",
  IndianRed2 = "#ee6363",
  IndianRed3 = "#cd5555",
  IndianRed4 = "#8b3a3a",
  Indigo = "#4b0082",
  Ivory = "#fffff0",
  Ivory1 = "#fffff0",
  Ivory2 = "#eeeee0",
  Ivory3 = "#cdcdc1",
  Ivory4 = "#8b8b83",
  Khaki = "#f0e68c",
  Khaki1 = "#fff68f",
  Khaki2 = "#eee685",
  Khaki3 = "#cdc673",
  Khaki4 = "#8b864e",
  Lavender = "#e6e6fa",
  LavenderBlush = "#fff0f5",
  LavenderBlush1 = "#fff0f5",
  LavenderBlush2 = "#eee0e5",
  LavenderBlush3 = "#cdc1c5",
  LavenderBlush4 = "#8b8386",
  LawnGreen = "#7cfc00",
  LemonChiffon = "#fffacd",
  LemonChiffon1 = "#fffacd",
  LemonChiffon2 = "#eee9bf",
  LemonChiffon3 = "#cdc9a5",
  LemonChiffon4 = "#8b8970",
  LightBlue = "#add8e6",
  LightBlue1 = "#bfefff",
  LightBlue2 = "#b2dfee",
  LightBlue3 = "#9ac0cd",
  LightBlue4 = "#68838b",
  LightCoral = "#f08080",
  LightCyan = "#e0ffff",
  LightCyan1 = "#e0ffff",
  LightCyan2 = "#d1eeee",
  LightCyan3 = "#b4cdcd",
  LightCyan4 = "#7a8b8b",
  LightGoldenrod = "#eedd82",
  LightGoldenrod1 = "#ffec8b",
  LightGoldenrod2 = "#eedc82",
  LightGoldenrod3 = "#cdbe70",
  LightGoldenrod4 = "#8b814c",
  LightGoldenrodYellow = "#fafad2",
  LightGray = "#d3d3d3",
  LightGreen = "#90ee90",
  LightGrey = "#d3d3d3",
  LightMagenta = "#ffbbff",
  LightPink = "#ffb6c1",
  LightPink1 = "#ffaeb9",
  LightPink2 = "#eea2ad",
  LightPink3 = "#cd8c95",
  LightPink4 = "#8b5f65",
  LightRed = "#ffbbbb",
  LightSalmon = "#ffa07a",
  LightSalmon1 = "#ffa07a",
  LightSalmon2 = "#ee9572",
  LightSalmon3 = "#cd8162",
  LightSalmon4 = "#8b5742",
  LightSeaGreen = "#20b2aa",
  LightSkyBlue = "#87cefa",
  LightSkyBlue1 = "#b0e2ff",
  LightSkyBlue2 = "#a4d3ee",
  LightSkyBlue3 = "#8db6cd",
  LightSkyBlue4 = "#607b8b",
  LightSlateBlue = "#8470ff",
  LightSlateGray = "#778899",
  LightSlateGrey = "#778899",
  LightSteelBlue = "#b0c4de",
  LightSteelBlue1 = "#cae1ff",
  LightSteelBlue2 = "#bcd2ee",
  LightSteelBlue3 = "#a2b5cd",
  LightSteelBlue4 = "#6e7b8b",
  LightYellow = "#ffffe0",
  LightYellow1 = "#ffffe0",
  LightYellow2 = "#eeeed1",
  LightYellow3 = "#cdcdb4",
  LightYellow4 = "#8b8b7a",
  Lime = "#00ff00",
  LimeGreen = "#32cd32",
  Linen = "#faf0e6",
  Magenta = "#ff00ff",
  Magenta1 = "#ff00ff",
  Magenta2 = "#ee00ee",
  Magenta3 = "#cd00cd",
  Magenta4 = "#8b008b",
  Maroon = "#800000",
  Maroon1 = "#ff34b3",
  Maroon2 = "#ee30a7",
  Maroon3 = "#cd2990",
  Maroon4 = "#8b1c62",
  MediumAquamarine = "#66cdaa",
  MediumBlue = "#0000cd",
  MediumOrchid = "#ba55d3",
  MediumOrchid1 = "#e066ff",
  MediumOrchid2 = "#d15fee",
  MediumOrchid3 = "#b452cd",
  MediumOrchid4 = "#7a378b",
  MediumPurple = "#9370db",
  MediumPurple1 = "#ab82ff",
  MediumPurple2 = "#9f79ee",
  MediumPurple3 = "#8968cd",
  MediumPurple4 = "#5d478b",
  MediumSeaGreen = "#3cb371",
  MediumSlateBlue = "#7b68ee",
  MediumSpringGreen = "#00fa9a",
  MediumTurquoise = "#48d1cc",
  MediumVioletRed = "#c71585",
  MidnightBlue = "#191970",
  MintCream = "#f5fffa",
  MistyRose = "#ffe4e1",
  MistyRose1 = "#ffe4e1",
  MistyRose2 = "#eed5d2",
  MistyRose3 = "#cdb7b5",
  MistyRose4 = "#8b7d7b",
  Moccasin = "#ffe4b5",
  NavajoWhite = "#ffdead",
  NavajoWhite1 = "#ffdead",
  NavajoWhite2 = "#eecfa1",
  NavajoWhite3 = "#cdb38b",
  NavajoWhite4 = "#8b795e",
  Navy = "#000080",
  NavyBlue = "#000080",
  NvimDarkBlue = "#004c73",
  NvimDarkCyan = "#007373",
  NvimDarkGray1 = "#07080d",
  NvimDarkGray2 = "#14161b",
  NvimDarkGray3 = "#2c2e33",
  NvimDarkGray4 = "#4f5258",
  NvimDarkGreen = "#005523",
  NvimDarkGrey1 = "#07080d",
  NvimDarkGrey2 = "#14161b",
  NvimDarkGrey3 = "#2c2e33",
  NvimDarkGrey4 = "#4f5258",
  NvimDarkMagenta = "#470045",
  NvimDarkRed = "#590008",
  NvimDarkYellow = "#6b5300",
  NvimLightBlue = "#a6dbff",
  NvimLightCyan = "#8cf8f7",
  NvimLightGray1 = "#eef1f8",
  NvimLightGray2 = "#e0e2ea",
  NvimLightGray3 = "#c4c6cd",
  NvimLightGray4 = "#9b9ea4",
  NvimLightGreen = "#b3f6c0",
  NvimLightGrey1 = "#eef1f8",
  NvimLightGrey2 = "#e0e2ea",
  NvimLightGrey3 = "#c4c6cd",
  NvimLightGrey4 = "#9b9ea4",
  NvimLightMagenta = "#ffcaff",
  NvimLightRed = "#ffc0b9",
  NvimLightYellow = "#fce094",
  OldLace = "#fdf5e6",
  Olive = "#808000",
  OliveDrab = "#6b8e23",
  OliveDrab1 = "#c0ff3e",
  OliveDrab2 = "#b3ee3a",
  OliveDrab3 = "#9acd32",
  OliveDrab4 = "#698b22",
  Orange = "#ffa500",
  Orange1 = "#ffa500",
  Orange2 = "#ee9a00",
  Orange3 = "#cd8500",
  Orange4 = "#8b5a00",
  OrangeRed = "#ff4500",
  OrangeRed1 = "#ff4500",
  OrangeRed2 = "#ee4000",
  OrangeRed3 = "#cd3700",
  OrangeRed4 = "#8b2500",
  Orchid = "#da70d6",
  Orchid1 = "#ff83fa",
  Orchid2 = "#ee7ae9",
  Orchid3 = "#cd69c9",
  Orchid4 = "#8b4789",
  PaleGoldenrod = "#eee8aa",
  PaleGreen = "#98fb98",
  PaleGreen1 = "#9aff9a",
  PaleGreen2 = "#90ee90",
  PaleGreen3 = "#7ccd7c",
  PaleGreen4 = "#548b54",
  PaleTurquoise = "#afeeee",
  PaleTurquoise1 = "#bbffff",
  PaleTurquoise2 = "#aeeeee",
  PaleTurquoise3 = "#96cdcd",
  PaleTurquoise4 = "#668b8b",
  PaleVioletRed = "#db7093",
  PaleVioletRed1 = "#ff82ab",
  PaleVioletRed2 = "#ee799f",
  PaleVioletRed3 = "#cd6889",
  PaleVioletRed4 = "#8b475d",
  PapayaWhip = "#ffefd5",
  PeachPuff = "#ffdab9",
  PeachPuff1 = "#ffdab9",
  PeachPuff2 = "#eecbad",
  PeachPuff3 = "#cdaf95",
  PeachPuff4 = "#8b7765",
  Peru = "#cd853f",
  Pink = "#ffc0cb",
  Pink1 = "#ffb5c5",
  Pink2 = "#eea9b8",
  Pink3 = "#cd919e",
  Pink4 = "#8b636c",
  Plum = "#dda0dd",
  Plum1 = "#ffbbff",
  Plum2 = "#eeaeee",
  Plum3 = "#cd96cd",
  Plum4 = "#8b668b",
  PowderBlue = "#b0e0e6",
  Purple = "#800080",
  Purple1 = "#9b30ff",
  Purple2 = "#912cee",
  Purple3 = "#7d26cd",
  Purple4 = "#551a8b",
  RebeccaPurple = "#663399",
  Red = "#ff0000",
  Red1 = "#ff0000",
  Red2 = "#ee0000",
  Red3 = "#cd0000",
  Red4 = "#8b0000",
  RosyBrown = "#bc8f8f",
  RosyBrown1 = "#ffc1c1",
  RosyBrown2 = "#eeb4b4",
  RosyBrown3 = "#cd9b9b",
  RosyBrown4 = "#8b6969",
  RoyalBlue = "#4169e1",
  RoyalBlue1 = "#4876ff",
  RoyalBlue2 = "#436eee",
  RoyalBlue3 = "#3a5fcd",
  RoyalBlue4 = "#27408b",
  SaddleBrown = "#8b4513",
  Salmon = "#fa8072",
  Salmon1 = "#ff8c69",
  Salmon2 = "#ee8262",
  Salmon3 = "#cd7054",
  Salmon4 = "#8b4c39",
  SandyBrown = "#f4a460",
  SeaGreen = "#2e8b57",
  SeaGreen1 = "#54ff9f",
  SeaGreen2 = "#4eee94",
  SeaGreen3 = "#43cd80",
  SeaGreen4 = "#2e8b57",
  SeaShell = "#fff5ee",
  Seashell1 = "#fff5ee",
  Seashell2 = "#eee5de",
  Seashell3 = "#cdc5bf",
  Seashell4 = "#8b8682",
  Sienna = "#a0522d",
  Sienna1 = "#ff8247",
  Sienna2 = "#ee7942",
  Sienna3 = "#cd6839",
  Sienna4 = "#8b4726",
  Silver = "#c0c0c0",
  SkyBlue = "#87ceeb",
  SkyBlue1 = "#87ceff",
  SkyBlue2 = "#7ec0ee",
  SkyBlue3 = "#6ca6cd",
  SkyBlue4 = "#4a708b",
  SlateBlue = "#6a5acd",
  SlateBlue1 = "#836fff",
  SlateBlue2 = "#7a67ee",
  SlateBlue3 = "#6959cd",
  SlateBlue4 = "#473c8b",
  SlateGray = "#708090",
  SlateGray1 = "#c6e2ff",
  SlateGray2 = "#b9d3ee",
  SlateGray3 = "#9fb6cd",
  SlateGray4 = "#6c7b8b",
  SlateGrey = "#708090",
  Snow = "#fffafa",
  Snow1 = "#fffafa",
  Snow2 = "#eee9e9",
  Snow3 = "#cdc9c9",
  Snow4 = "#8b8989",
  SpringGreen = "#00ff7f",
  SpringGreen1 = "#00ff7f",
  SpringGreen2 = "#00ee76",
  SpringGreen3 = "#00cd66",
  SpringGreen4 = "#008b45",
  SteelBlue = "#4682b4",
  SteelBlue1 = "#63b8ff",
  SteelBlue2 = "#5cacee",
  SteelBlue3 = "#4f94cd",
  SteelBlue4 = "#36648b",
  Tan = "#d2b48c",
  Tan1 = "#ffa54f",
  Tan2 = "#ee9a49",
  Tan3 = "#cd853f",
  Tan4 = "#8b5a2b",
  Teal = "#008080",
  Thistle = "#d8bfd8",
  Thistle1 = "#ffe1ff",
  Thistle2 = "#eed2ee",
  Thistle3 = "#cdb5cd",
  Thistle4 = "#8b7b8b",
  Tomato = "#ff6347",
  Tomato1 = "#ff6347",
  Tomato2 = "#ee5c42",
  Tomato3 = "#cd4f39",
  Tomato4 = "#8b3626",
  Turquoise = "#40e0d0",
  Turquoise1 = "#00f5ff",
  Turquoise2 = "#00e5ee",
  Turquoise3 = "#00c5cd",
  Turquoise4 = "#00868b",
  Violet = "#ee82ee",
  VioletRed = "#d02090",
  VioletRed1 = "#ff3e96",
  VioletRed2 = "#ee3a8c",
  VioletRed3 = "#cd3278",
  VioletRed4 = "#8b2252",
  WebGray = "#808080",
  WebGreen = "#008000",
  WebGrey = "#808080",
  WebMaroon = "#800000",
  WebPurple = "#800080",
  Wheat = "#f5deb3",
  Wheat1 = "#ffe7ba",
  Wheat2 = "#eed8ae",
  Wheat3 = "#cdba96",
  Wheat4 = "#8b7e66",
  White = "#ffffff",
  WhiteSmoke = "#f5f5f5",
  X11Gray = "#bebebe",
  X11Green = "#00ff00",
  X11Grey = "#bebebe",
  X11Maroon = "#b03060",
  X11Purple = "#a020f0",
  Yellow = "#ffff00",
  Yellow1 = "#ffff00",
  Yellow2 = "#eeee00",
  Yellow3 = "#cdcd00",
  Yellow4 = "#8b8b00",
  YellowGreen = "#9acd32"
}

]]
